### ISSUE TITLE
Definir estilização do código e configurar editor

### ISSUE THREAD

**Issue by salatvieira** [salatvieira/clone-tabnews#2]
- [x] Ligar sincronização do Editor
- [x] Configurar o EditorConfig
- [x] Configurar o Prettier
- [x] Configura o Prettier Ignore

**Comment by filipedeschamps** [comment]
Sensacional!!! Esta vai ser a primeira issue que vamos trabalhar nos próximos dias 🤝

**Comment by salatvieira** [comment]
- [ ] Ligar sincronização do Editor
- [ ] Configurar o EditorConfig
- [ ] Configurar o Prettier
